---
- name: "Task 2 YAML: Mount local disk"
  vars:
    # "Felcsatolás fstab-ba /data/dir-be"
    fstab_mount_dir: '/data/dir'
    src_dev: '/dev/vdb'
    src_dir: '/dev/vdb1'
  tasks:
    - name: do_create_mount_dir
    ansible.builtin.file:
        file: '{{ fstab_mount_dir }}'
        state: directory
    
    - name: do_create_local_disk_partition
    community.general.parted:
        device: '{{ src_dev }}'
        number: 1
        fs_type: ext4
        state: present
    
    - name: do_mount_local_disk_fstab
    ansible.posix.mount:
        path: '{{ fstab_mount_dir }}'
        src: '{{ src_dir }}'
        fstype: ext4
        opts: defaults
        state: mounted
    notify:
    - local_disk_fstab_mount_done
  handlers:
    -name: local_disk_fstab_mount_done
    ansible.builtin.debug:
        msg: 'Local disk mounted in the specified directory'
