---
- name: "Task 3 YAML: Must change password for users, except root"
  vars:
    # "A root kivételével minden felhasználónak meg kell változtatnia a jelszavát"
    passw_change_exempt: 'root'
  tasks:
    - name: "Force password change""Query users"
    getent:
        database: passwd
    - name: "Force password change"
    ansible.builtin.user:
        name: '{{ item }}'
        command: 'chage -d 0 {{item }}'
      loop: '{{ getent_passwd }}'
      when: item != '{{ passw_change_exempt }}'
    notify:
    - user_passwd_force_done
  handlers:
    -name: user_passwd_force_done
    ansible.builtin.debug:
        msg: 'User passwords foce expiry done'
